# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbf603471ae2bd8f9011f9e116b598e1d340f276db9b85a0428f0cdae6545c4d3498364a1fa2848b208c4b26aa17dc093c4b522c231eb6b2bdad3af582040705

test:
  secret_key_base: babed6d283b0f1b6da754800911cf3e7013eff6bb4ea7378d6aad9c32f33521f48eccbafd533055854e76d24b151649fb97e34e0018e4c72419df61b9e6079ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
